databases:
  - name: candystore_db
    databaseName: candystore
    user: candystore_user

services:
  - type: web
    name: candystore
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn candystore.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: candystore_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
